In [1]:
import numpy as np
import cv2
import os
from PIL import Image
testing = True

if __name__ == '__main__' and testing:
    os.chdir(r'C:\Users\jesus\Pictures\Saved Pictures')
    image_list = os.listdir(os.getcwd())
    for image in image_list:
        try:
            loaded_image = Image.open(image)
            loaded_image.show()
        except:
            continue


In [2]:
np

<module 'numpy' from 'c:\\Users\\jesus\\Documents\\WorkFiles\\PythonCode\\TF2_personal_projects\\git_env\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
loaded_image = Image.open(os.listdir()[0])

In [4]:
loaded_image.size

(1201, 892)

In [5]:
array_image = np.asarray(loaded_image)

In [6]:
array_image.shape

(892, 1201, 4)

In [7]:
print(array_image)

[[[255 239  63 255]
  [255 239  63 255]
  [255 239  63 255]
  ...
  [223 223 223 255]
  [223 223 223 255]
  [223 223 223 255]]

 [[255 237  61 255]
  [255 237  61 255]
  [255 237  61 255]
  ...
  [223 223 223 255]
  [223 223 223 255]
  [223 223 223 255]]

 [[255 236  59 255]
  [255 236  59 255]
  [255 236  59 255]
  ...
  [223 223 223 255]
  [223 223 223 255]
  [223 223 223 255]]

 ...

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]

 [[255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]
  ...
  [255 255 255 255]
  [255 255 255 255]
  [255 255 255 255]]]


In [8]:
import tensorflow as tf

In [9]:
tf.convert_to_tensor(array_image)

<tf.Tensor: shape=(892, 1201, 4), dtype=uint8, numpy=
array([[[255, 239,  63, 255],
        [255, 239,  63, 255],
        [255, 239,  63, 255],
        ...,
        [223, 223, 223, 255],
        [223, 223, 223, 255],
        [223, 223, 223, 255]],

       [[255, 237,  61, 255],
        [255, 237,  61, 255],
        [255, 237,  61, 255],
        ...,
        [223, 223, 223, 255],
        [223, 223, 223, 255],
        [223, 223, 223, 255]],

       [[255, 236,  59, 255],
        [255, 236,  59, 255],
        [255, 236,  59, 255],
        ...,
        [223, 223, 223, 255],
        [223, 223, 223, 255],
        [223, 223, 223, 255]],

       ...,

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255]],

       [[255, 255, 255, 255],
        [255, 255, 255, 255],
        [255, 255, 255, 255],
        ...,
        [255, 255, 255, 255],
        [255, 255, 2

In [10]:
tf.convert_to_tensor(array_image) / 255

<tf.Tensor: shape=(892, 1201, 4), dtype=float32, numpy=
array([[[1.        , 0.9372549 , 0.24705882, 1.        ],
        [1.        , 0.9372549 , 0.24705882, 1.        ],
        [1.        , 0.9372549 , 0.24705882, 1.        ],
        ...,
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ],
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ],
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ]],

       [[1.        , 0.92941177, 0.23921569, 1.        ],
        [1.        , 0.92941177, 0.23921569, 1.        ],
        [1.        , 0.92941177, 0.23921569, 1.        ],
        ...,
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ],
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ],
        [0.8745098 , 0.8745098 , 0.8745098 , 1.        ]],

       [[1.        , 0.9254902 , 0.23137255, 1.        ],
        [1.        , 0.9254902 , 0.23137255, 1.        ],
        [1.        , 0.9254902 , 0.23137255, 1.        ],
        ...,
        [0.8745098 , 0.8745098 

In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
from tensorflow.keras.preprocessing.image import load_img

In [3]:
import warnings

In [4]:
img = load_img(os.listdir()[0])

NameError: name 'os' is not defined

In [5]:
import os

In [6]:
img = load_img(os.listdir()[0])

PermissionError: [Errno 13] Permission denied: '.ipynb_checkpoints'